### PR TITLE
Fix for illegal character on windows. Closes #315.

### LINKED ISSUE #315: Windows compatibility
Released a little CLI build tool today based on Accord and people are reporting errors on Windows: https://www.reddit.com/r/Frontend/comments/69yb68/pingy_cli_the_simple_frontend_build_tool/dhaomno/

Looks like possibly the path `lib\adapters\pug\>2.0.0-beta.js` is invalid on Windows [because of the greater-than character](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396). I don't have access to a windows machine at the moment. Any thoughts on how to remedy this?

### PR DESCRIPTION
**Pull request by davej**
I believe this will fix #315. It passes the online SemVer check. I think it's reasonable to assume that the API won't change for `2.x`.

image

### CODE REVIEW

**Comment by jescalan** [comment]
Good catch, thank you!

**Comment by davej** [comment]
You're a star 👍 

Any chance of a patch release? BTW, always happy to help with publishing/maintenance/etc.. if you want to add me as a collaborator on github + npm.

**Comment by jescalan** [comment]
Already released. And yeah I would definitely be interested in adding you as a maintainer here -- maybe we can chat sometime soon about this?

**Comment by davej** [comment]
> Already released.

Awesome.

> And yeah I would definitely be interested in adding you as a maintainer here -- maybe we can chat sometime soon about this?

Sure, whenever suits you. Also check out [Pingy CLI](https://pin.gy/cli/), Accord is doing all the compilation magic in the background :)

**Comment by davej** [comment]
@jescalan Looks like you forgot to brew the coffeescript again 😃

**Comment by jescalan** [comment]
hahah oh man, i am really bad at this. fixing now

**Comment by jescalan** [comment]
done

**Comment by davej** [comment]
I think my next PR will include a `prepublish` script! 👍

**Comment by jescalan** [comment]
Haha don't even start down that rabbit hole, npm has no actual prepublish hook, unfortunately.

**Comment by davej** [comment]
As of `npm4`, they have `prepublishOnly` and `prepare`. I believe `prepublishOnly` will be the new `prepublish` in some future version.

**Comment by jescalan** [comment]
Yep, neither of them do what you want. Trust me, I spent a long time on this. This is as close as you'll get: https://github.com/sindresorhus/np/issues/155

**Comment by davej** [comment]
Does `prepare` not do what you need?

**Comment by davej** [comment]
ah wait, runs on `npm install`, I see your problem.

**Comment by jescalan** [comment]
Haha you can go down the same rabbit hole if you want, or you can take my word for it 😉

**Comment by davej** [comment]
Don't have time at the moment but would you entertain a PR for JS rewrite some time in the future? Shouldn't be too much hassle with a coffee to es6 compiler and a bit of manual editing.

**Comment by jescalan** [comment]
I would actually love it. To be honest, I am not using accord anymore for active projects, which is the only reason I'm not as active in maintaining it. I have gone the way of using postcss / babel / reshape, which can flex to fit any syntax within a single engine. Really, I think the life of single project compile to target languages is coming to an end -- any future syntax updates would be better implemented through one of the above three transformation engines.

BUT I can definitely see why you are using this, and I know there are still a lot of people using coffeescript and sass and pug and such, so I'm happy you are still working on it!

**Comment by davej** [comment]
You're probably correct in the long term, especially for hardcore web devs. It takes a long time for the ship to turn though and the learning curve for those tools is pretty steep for people who don't have a lot of dev experience.

That's where I'm going with Pingy CLI, trying to help out those who don't want to invest tons of time in their build toolchain but just want the basics (e.g. Sass with source maps, Live Reload and asset minification) without needing to do any configuration.

Accord ES6 Rewrite is on my todo list, will probably drop support for node < 6 at the same time if it's ok with you?

**Comment by jescalan** [comment]
Definitely. Although to be fair if you're just starting I don't think that using es6 over coffee, or cssnext over sass would be too much of a difference. I think really the sector that would still value something like accord is people who have already become accustomed to sass/coffee and are not ready to change. But like you said these things take a while to set in, and there are still a lot of people using them _at the moment_.

[This little example](https://github.com/static-dev/spike-basic-example/blob/master/app.js) shows how little config it takes to get up and running on these tools though. When it comes to using plugin platforms (babel/postcss/reshape), minimizing config depends on using standard configurations, or presets. Since plugin platform tools can be infinitely configured in different ways, in order to get the consistency that comes with fixed spec languages, standard config packages like babel's `preset-env` which are configured to do the trick for the vast majority of people are a great solution. And for those seeking more advanced configurations, they are free to configure as they wish, with limitless flexibility.

And yeah, supporting only node 6+ is 100% ok by me!

**Pull request merged**
