### PR TITLE
Replaced Object.assign with lodash.assign for compatibility with pre-node-v4 (ref gulp-stylus)

### PR DESCRIPTION
**Pull request by robertdbailey**
Just wanted to help gulp-stylus update their version of accord to the current one, so they can hopefully not remove support for versions of node before v4.  Thanks!  @jescalan @stevelacy

ref: https://github.com/stevelacy/gulp-stylus/pull/184

### CODE REVIEW

**Comment by stevelacy** [comment]
Grr... looks like the project `marc/node_modules/datastore` should have had a minor (major really) bump but got a patch which is causing the build to fail: https://github.com/bredele/datastore/commit/ee03f5545c9e8a966a7844fb5a6f402017af8e96

**Comment by jescalan** [comment]
Its ok, I can patch this shortly

**Comment by jescalan** [comment]
Ah never mind, the breakage in this library goes pretty deep. I'll ignore those tests for now and move forward with this PR

**Comment by jescalan** [comment]
Ok so I'll ship this out, but honestly it will need to be changed back fairly soon. v4 and v6 are the LTS versions now, 0.10 is unmaintained, and 0.12 is well on the way out. For those on 0.12, it's getting towards critical to start upgrading to v4!

**Comment by jescalan** [comment]
I mean, actually we really only have 2 months until 0.12 is unmaintained. Do you think this is really worth it?

**Comment by stevelacy** [comment]
Want me to only support v4+ on `gulp-stylus`? 
That would be a quick fix

**Comment by stevelacy** [comment]
I am now only supporting v4.2.0LTS+ on `gulp-stylus`

**Comment by jescalan** [comment]
@stevelacy yeah I think that was the right move for sure 👍

**Pull request closed without merging**
