### PR TITLE
Expose abstract_mapper (See: #191)

### PR DESCRIPTION
**Pull request by matthew-dean**

### CODE REVIEW

**Comment by jescalan** [comment]
Could you squash these into a single commit?

**Comment by jescalan** [comment]
ping @matthew-dean

**Comment by davej** [comment]
@jescalan You might be aware of this already but you can squash and merge from within github with one-click if you like 😃

**Comment by jescalan** [comment]
Ah nice! Honestly I thought that was an april fools when they released it because it seems kind of dangerous haha. Ok will do this instead.

**Comment by davej** [comment]
😃 It maintains the commit history on the PR so it's actually quite nice compared with doing it on the branch IMHO.

**Pull request merged**
