### PR TITLE
Move uglify-js to devdeps + fix tests

### LINKED ISSUE #341: Remove uglify-js from dependencies
Hello,

I have `accord` listed in my dependencies because it's used from `gulp-less`.
`accord` makes npm install uglify-js@2.x for no reason, because it's listed in dependencies and not peer or dev dependencies.

My idea of a fix would be to move `uglify-js` to `devDependencies` at it seems to be your convention, but I believe `peerDependencies` would be even better, correct me if I'm wrong (thus #339 is maybe related).

### PR DESCRIPTION
**Pull request by saveman71**
Fixes #341

### CODE REVIEW

**Comment by saveman71** [comment]
Okay, this is weird, local tests were failing because of these backticks, and I had now idea where they were coming from, so I added them to the expected outputs where relevant. I'll remove them then, any idea of the origin?

**Comment by jescalan** [comment]
Yeah sometimes frameworks will update and their output will change slightly - this is normal. Thanks for fixing! This looks great - are you ready for review or still working?

**Comment by saveman71** [comment]
@jescalan RTM for me!

**Comment by saveman71** [comment]
@jescalan up! :slightly_smiling_face:

**Comment by Yothin8888** [comment]
https://github.com/LaBelleAssiette/accord.git

**Comment by Yothin8888** [comment]
https://github.com/LaBelleAssiette/accord.git

**Pull request merged**
