### PR TITLE
[Ready for merge] bugfix: `util.inspect` returns a string and obscures some errors

### PR DESCRIPTION
**Pull request by davej**
Closing #304 in favour of this.

In short, `util.inspect` returns a string representation of an object that only goes two levels deep. This obscures all inequalities that are deeper than two levels.

This causes a number of new failing tests but I believe it is what was originally intended. This PR will include fixes for tests that fail as a result of this fix.

### CODE REVIEW

**Comment by davej** [comment]
Ok, all tests are passing now.

Curiously, they pass if you install with yarn but a couple (myth and toffee) fail if you install with npm (v4.1.2).

Yarn and npm must install different versions of `myth` and `toffee` for some reason. Anyway that's a PR for another day.

**Comment by jescalan** [comment]
Beautiful, thank you! 👬

**Comment by davej** [comment]
👍 Thanks! Would it be possible to cut a release with the new Pug stuff whenever you get the chance?

**Comment by jescalan** [comment]
@davej yeah sorry for the delay! running it right now 😁

**Comment by davej** [comment]
@jescalan Thanks! Looks like it's still on 26.4 though.

**Comment by jescalan** [comment]
@davej sorry for the extra holdup, just published 0.27.0 today, including upgrades to support all the most recent versions of adapters 🙌

**Comment by davej** [comment]
@jescalan Woops, I think you forgot to compile the coffeescript files when publishing `0.27.0`. Any chance of a patch release, please?

**Comment by jescalan** [comment]
Hahah oh man, I suck. This is like the only project I still maintain that uses coffeescript, sorry! Will do

**Comment by jescalan** [comment]
ok @davej done!

**Pull request merged**
